name: Nexss CI

on:
  push:
    branches: [master]

jobs:
  build:
    # if: always()
    # if: success() || failure()
    continue-on-error: true
    strategy:
      matrix:
        os:
          [windows-latest, windows-2019, ubuntu-latest, macos-latest, macos-12]
        node-version: ["16.x", "18.x", "20.x", "22.x", "23.x"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - uses: actions/cache@v4
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Install packages
        if: steps.restore-build.outputs.cache-hit != 'true'
        run: |
          npx @nexssp/os update # updates packages os dependent
          npm install -g .
          npm run build --if-present
      - run: nexss
      - run: nexss Id
      - run: nexss Output/End "ABCDEF"
      # ls /root/.nexss/packages/
      # nexss Nexss/Test/Sequences --seq=mytestdata --debug
      # - run: Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH

      - run: yarn test
